FROM node:20-alpine
WORKDIR /app

COPY config/package.json ./
COPY config/tsconfig.json ./
COPY config/nest-cli.json ./
COPY config/logger.config.ts ./config/

RUN npm i

COPY apps/gateway ./apps/gateway
COPY common ./common
COPY core ./core

CMD ["npm", "run", "start:dev", "gateway"]